engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmd.xml"
    checks:
      Naming/ShortMethodName:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
  - config/**/*
  - examples/**/*
  - tests/**/*
  - "**/vendor/**/*"
