# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "CI"

jobs:

  tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-binary:
          - php7.4
          - php8.0

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install dependencies with composer"
        run: ${{ matrix.php-binary }} $(which composer) update --no-interaction --no-progress --no-suggest

      - name: "Run unit tests with phpunit"
        run: ${{ matrix.php-binary }} vendor/bin/phpunit --configuration=phpunit.xml

      - name: "Send code coverage report to Codecov.io"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
